name: fake_store_v1
description: "A Shopping Cart Application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  badges: ^3.1.2
  provider: ^6.1.2
  http: ^1.2.2
  cached_network_image: ^3.3.1
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/